using System;

namespace zzre;

[AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
public sealed class ConfigurationAttribute : Attribute
{
    /// <summary>
    /// An explicit key for the configuration value, will be auto-generated by class- and field-name if left empty.
    /// </summary>
    public string Key { get; init; } = "";

    /// <summary>
    /// A description for humans shown in tooling for this configuration value
    /// </summary>
    public string Description { get; init; } = "";

    /// <summary>
    /// A minimal value for numeric configuration values used in tooling for validation
    /// </summary>
    public double Min { get; init; } = double.NegativeInfinity;

    /// <summary>
    /// A maximal value for numeric configuration values used in tooling for validation
    /// </summary>
    public double Max { get; init; } = double.PositiveInfinity;

    /// <summary>
    /// Whether this numeric configuration value should be constrained to integers
    /// </summary>
    public bool IsInteger { get; init; }
}
