name: Main branch build

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/build.yml
    with:
      runs-on: ${{ matrix.os }}
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: TODO to Issue
      uses: alstr/todo-to-issue-action@v4.3
